export const metadata = {
  title: 'Terms of Service – Faro MiniGPT',
};

export default function TermsPage() {
  const updated = 'April 15, 2026';

  return (
    <main style={{ maxWidth: 720, margin: '0 auto', padding: '2rem 1rem', fontFamily: 'sans-serif', lineHeight: 1.7 }}>
      <h1>Terms of Service</h1>
      <p><em>Last updated: {updated}</em></p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By using Faro MiniGPT (the &ldquo;Service&rdquo;), you agree to these Terms of Service.
        If you do not agree, please do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Faro is an AI companion that helps underrepresented entrepreneurs discover the
        best places to start and grow their businesses—based on real opportunity, not
        guesswork. The Service provides city recommendations, comparisons, grants, and
        actionable insights through ChatGPT Actions.
      </p>

      <h2>3. Use of the Service</h2>
      <p>
        You may use the Service for lawful purposes only. You agree not to:
      </p>
      <ul>
        <li>Use the Service in any way that violates applicable laws or regulations</li>
        <li>Attempt to gain unauthorized access to the Service or its systems</li>
        <li>Use the Service to transmit malicious code or harmful content</li>
        <li>Abuse, harass, or harm other users</li>
      </ul>

      <h2>4. AI-Generated Content</h2>
      <p>
        Recommendations and insights provided by the Service are generated by AI models
        (Google Gemini, OpenAI, or Anthropic Claude) and are for informational purposes only.
        We do not guarantee the accuracy, completeness, or suitability of AI-generated content
        for your specific business needs. Always verify critical information independently.
      </p>

      <h2>5. No Business or Investment Advice</h2>
      <p>
        The Service provides general information and recommendations. It does not constitute
        professional business, legal, financial, or investment advice. Consult qualified
        professionals for specific advice tailored to your situation.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Faro and its operators shall not be liable
        for any indirect, incidental, special, consequential, or punitive damages arising
        from your use of the Service, including but not limited to business losses,
        lost profits, or data loss.
      </p>

      <h2>7. Service Availability</h2>
      <p>
        We strive to keep the Service available, but we do not guarantee uninterrupted access.
        The Service may be temporarily unavailable due to maintenance, updates, or technical
        issues with third-party AI providers.
      </p>

      <h2>8. Privacy</h2>
      <p>
        Your use of the Service is also governed by our{' '}
        <a href="/privacy" style={{ color: '#0070f3' }}>Privacy Policy</a>.
      </p>

      <h2>9. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the Service after
        changes constitutes acceptance of the updated Terms. The &ldquo;Last updated&rdquo;
        date reflects the most recent revision.
      </p>

      <h2>10. Termination</h2>
      <p>
        We reserve the right to suspend or terminate access to the Service at any time,
        with or without notice, for any reason including violation of these Terms.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the United States. Any disputes arising
        from these Terms or use of the Service shall be resolved in accordance with
        applicable law.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms? Email{' '}
        <a href="mailto:team@farosmart.com" style={{ color: '#0070f3' }}>team@farosmart.com</a>.
      </p>
    </main>
  );
}
